openapi: '3.0.1'
info:
  title: Export definitions
  version: 1.0.0
components:
  schemas:
    PolygonalGeometry:
      description: GeoJSON Polygonal Geometry
      discriminator:
        propertyName: type
      type: object
      oneOf:
        - $ref: '../core/geojson.yaml#/components/schemas/Polygon'
        - $ref: '../core/geojson.yaml#/components/schemas/MultiPolygon'

    RoiFeatureProperties:
      type: object
      description: Properties of a Region of Interest (ROI) feature
      properties:
        maxResolutionDeg:
          description: Maximum resolution in degrees
          type: number
          minimum: 3.35276126861572e-7
          maximum: 0.703125
          format: double
        minResolutionDeg:
          description: Minimum resolution in degrees
          type: number
          minimum: 3.35276126861572e-7
          maximum: 0.703125
          format: double

    PolygonalFeatureBase:
      type: object
      description: GeoJson Feature
      properties:
        type:
          type: string
          enum:
            - Feature
        geometry:
          $ref: '#/components/schemas/PolygonalGeometry'
        bbox:
          $ref: '../core/geojson.yaml#/components/schemas/BBox'
      required:
        - type
        - geometry

    PolygonalFeatureCollectionBase:
      type: object
      description: GeoJson Feature collection
      properties:
        type:
          type: string
          enum:
            - FeatureCollection
        bbox:
          $ref: '../core/geojson.yaml#/components/schemas/BBox'
      required:
        - type
        - features
