on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Init nodejs
        uses: ./.github/actions/init-npm
      - run: npm install -g npm
      - name: Get package version and branch
        id: package-info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
      - name: Publish to npm
        run: |
          echo "is pre-release: ${{ github.event.release.prerelease }}"
          echo "publish triggered on: ${{ github.ref_type }}"
          if [[ "${{ github.ref_type }}" == "tag" ]] &&
            [[ "${{ github.event.release.prerelease }}" == "true" ]] &&
            [[ "${{ github.ref_name }}" == "${{ steps.package-info.outputs.version }}" ]]; then
            echo "publishing prerelease with alpha tag from tag"
            # npm publish --access public --tag alpha
          elif [[ "${{ github.ref_type }}" == "branch" ]] &&
            [[ "${{ github.ref_name }}" == *"alpha"* ]]; then
            echo "publishing prerelease with alpha tag from branch"
            # npm publish --access public --tag alpha
          else
            echo "publishing standard release"
            # npm publish --access public
          fi
